#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */

/* RT-Thread Kernel */

#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 8
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 512
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 512

/* kservice optimization */

#define RT_KSERVICE_USING_STDLIB
/* end of kservice optimization */
#define RT_DEBUG

/* Inter-Thread communication */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
/* end of Inter-Thread communication */

/* Memory Management */

#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_MEMTRACE
#define RT_USING_HEAP
/* end of Memory Management */

/* Kernel Device Object */

#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 512
#define RT_CONSOLE_DEVICE_NAME "uart6"
/* end of Kernel Device Object */
#define RT_VER_NUM 0x50001
/* end of RT-Thread Kernel */
#define RT_USING_HW_ATOMIC
#define RT_USING_CPU_FFS
#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M4

/* RT-Thread Components */

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 10
#define RT_USING_MSH
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 4096
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_CMD_SIZE 80
#define MSH_USING_BUILT_IN_COMMANDS
#define FINSH_USING_DESCRIPTION
#define FINSH_ARG_MAX 10

/* DFS: device virtual file system */

#define RT_USING_DFS
#define DFS_USING_POSIX
#define DFS_USING_WORKDIR
#define DFS_FD_MAX 16
#define RT_USING_DFS_V1
#define DFS_FILESYSTEMS_MAX 4
#define DFS_FILESYSTEM_TYPES_MAX 4
#define RT_USING_DFS_ELMFAT

/* elm-chan's FatFs, Generic FAT Filesystem Module */

#define RT_DFS_ELM_CODE_PAGE 437
#define RT_DFS_ELM_WORD_ACCESS
#define RT_DFS_ELM_USE_LFN_3
#define RT_DFS_ELM_USE_LFN 3
#define RT_DFS_ELM_LFN_UNICODE_0
#define RT_DFS_ELM_LFN_UNICODE 0
#define RT_DFS_ELM_MAX_LFN 255
#define RT_DFS_ELM_DRIVES 2
#define RT_DFS_ELM_MAX_SECTOR_SIZE 512
#define RT_DFS_ELM_REENTRANT
#define RT_DFS_ELM_MUTEX_TIMEOUT 3000
/* end of elm-chan's FatFs, Generic FAT Filesystem Module */
#define RT_USING_DFS_DEVFS
/* end of DFS: device virtual file system */

/* Device Drivers */

#define RT_USING_DEVICE_IPC
#define RT_UNAMED_PIPE_NUMBER 64
#define RT_USING_SYSTEM_WORKQUEUE
#define RT_SYSTEM_WORKQUEUE_STACKSIZE 2048
#define RT_SYSTEM_WORKQUEUE_PRIORITY 23
#define RT_USING_SERIAL
#define RT_USING_SERIAL_V1
#define RT_SERIAL_USING_DMA
#define RT_SERIAL_RB_BUFSZ 1024
#define RT_USING_I2C
#define RT_USING_I2C_BITOPS
#define RT_USING_PIN
#define RT_USING_PWM
#define RT_USING_RTC
#define RT_USING_SDIO
#define RT_SDIO_STACK_SIZE 512
#define RT_SDIO_THREAD_PRIORITY 15
#define RT_MMCSD_STACK_SIZE 1024
#define RT_MMCSD_THREAD_PREORITY 22
#define RT_MMCSD_MAX_PARTITION 16
#define RT_USING_SPI
#define RT_USING_WDT
#define RT_USING_SENSOR
#define RT_USING_SENSOR_CMD
#define RT_USING_TOUCH
#define RT_TOUCH_PIN_IRQ
#define RT_USING_WIFI
#define RT_WLAN_DEVICE_STA_NAME "wlan0"
#define RT_WLAN_DEVICE_AP_NAME "wlan1"
#define RT_WLAN_SSID_MAX_LENGTH 32
#define RT_WLAN_PASSWORD_MAX_LENGTH 32
#define RT_WLAN_DEV_EVENT_NUM 2
#define RT_WLAN_MANAGE_ENABLE
#define RT_WLAN_SCAN_WAIT_MS 10000
#define RT_WLAN_CONNECT_WAIT_MS 10000
#define RT_WLAN_SCAN_SORT
#define RT_WLAN_MSH_CMD_ENABLE
#define RT_WLAN_AUTO_CONNECT_ENABLE
#define AUTO_CONNECTION_PERIOD_MS 2000
#define RT_WLAN_CFG_ENABLE
#define RT_WLAN_CFG_INFO_MAX 3
#define RT_WLAN_PROT_ENABLE
#define RT_WLAN_PROT_NAME_LEN 8
#define RT_WLAN_PROT_MAX 2
#define RT_WLAN_DEFAULT_PROT "lwip"
#define RT_WLAN_PROT_LWIP_ENABLE
#define RT_WLAN_PROT_LWIP_NAME "lwip"
#define RT_WLAN_WORK_THREAD_ENABLE
#define RT_WLAN_WORKQUEUE_THREAD_NAME "wlan"
#define RT_WLAN_WORKQUEUE_THREAD_SIZE 2048
#define RT_WLAN_WORKQUEUE_THREAD_PRIO 15

/* Using USB */

/* end of Using USB */
/* end of Device Drivers */

/* C/C++ and POSIX layer */

#define RT_LIBC_DEFAULT_TIMEZONE 8

/* POSIX (Portable Operating System Interface) layer */

#define RT_USING_POSIX_FS
#define RT_USING_POSIX_DEVIO
#define RT_USING_POSIX_POLL
#define RT_USING_POSIX_SELECT
#define RT_USING_POSIX_SOCKET

/* Interprocess Communication (IPC) */

#define RT_USING_POSIX_PIPE
#define RT_USING_POSIX_PIPE_SIZE 512

/* Socket is in the 'Network' category */

/* end of Interprocess Communication (IPC) */
/* end of POSIX (Portable Operating System Interface) layer */
#define RT_USING_CPLUSPLUS
/* end of C/C++ and POSIX layer */

/* Network */

#define RT_USING_SAL
#define SAL_INTERNET_CHECK

/* Docking with protocol stacks */

#define SAL_USING_LWIP
#define SAL_USING_TLS
/* end of Docking with protocol stacks */
#define SAL_USING_POSIX
#define RT_USING_NETDEV
#define NETDEV_USING_IFCONFIG
#define NETDEV_USING_PING
#define NETDEV_USING_NETSTAT
#define NETDEV_USING_AUTO_DEFAULT
#define NETDEV_IPV4 1
#define NETDEV_IPV6 0
#define RT_USING_LWIP
#define RT_USING_LWIP203
#define RT_USING_LWIP_VER_NUM 0x20003
#define RT_LWIP_MEM_ALIGNMENT 4
#define RT_LWIP_IGMP
#define RT_LWIP_ICMP
#define RT_LWIP_DNS
#define RT_LWIP_DHCP
#define IP_SOF_BROADCAST 1
#define IP_SOF_BROADCAST_RECV 1

/* Static IPv4 Address */

#define RT_LWIP_IPADDR "192.168.1.30"
#define RT_LWIP_GWADDR "192.168.1.1"
#define RT_LWIP_MSKADDR "255.255.255.0"
/* end of Static IPv4 Address */
#define RT_LWIP_UDP
#define RT_LWIP_TCP
#define RT_LWIP_RAW
#define RT_MEMP_NUM_NETCONN 8
#define RT_LWIP_PBUF_NUM 16
#define RT_LWIP_RAW_PCB_NUM 4
#define RT_LWIP_UDP_PCB_NUM 4
#define RT_LWIP_TCP_PCB_NUM 4
#define RT_LWIP_TCP_SEG_NUM 40
#define RT_LWIP_TCP_SND_BUF 8196
#define RT_LWIP_TCP_WND 8196
#define RT_LWIP_TCPTHREAD_PRIORITY 10
#define RT_LWIP_TCPTHREAD_MBOX_SIZE 8
#define RT_LWIP_TCPTHREAD_STACKSIZE 1024
#define RT_LWIP_ETHTHREAD_PRIORITY 12
#define RT_LWIP_ETHTHREAD_STACKSIZE 1024
#define RT_LWIP_ETHTHREAD_MBOX_SIZE 8
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define SO_REUSE 1
#define LWIP_SO_RCVTIMEO 1
#define LWIP_SO_SNDTIMEO 1
#define LWIP_SO_RCVBUF 1
#define LWIP_SO_LINGER 0
#define LWIP_NETIF_LOOPBACK 0
#define RT_LWIP_USING_PING
/* end of Network */

/* Utilities */

/* end of Utilities */
/* end of RT-Thread Components */

/* RT-Thread online packages */

/* IoT - internet of things */

#define PKG_USING_PAHOMQTT
#define PAHOMQTT_PIPE_MODE
#define PKG_USING_PAHOMQTT_EXAMPLE
#define RT_PKG_MQTT_THREAD_STACK_SIZE 4096
#define PKG_PAHOMQTT_SUBSCRIBE_HANDLERS 1
#define MQTT_DEBUG
#define PKG_USING_PAHOMQTT_LATEST
#define PKG_USING_WEBCLIENT
#define WEBCLIENT_USING_MBED_TLS
#define PKG_USING_WEBCLIENT_V220
#define PKG_WEBCLIENT_VER_NUM 0x20200

/* Wi-Fi */

/* Marvell WiFi */

/* end of Marvell WiFi */

/* Wiced WiFi */

/* end of Wiced WiFi */
#define PKG_USING_RW007
#define PKG_USING_RW007_V210
#define RW007_NOT_USE_EXAMPLE_DRIVERS
#define RW007_SPI_MAX_HZ 25000000

/* CYW43012 WiFi */

/* end of CYW43012 WiFi */

/* BL808 WiFi */

/* end of BL808 WiFi */

/* CYW43439 WiFi */

/* end of CYW43439 WiFi */
/* end of Wi-Fi */
#define PKG_USING_NETUTILS
#define PKG_NETUTILS_NTP
#define NTP_USING_AUTO_SYNC
#define NTP_AUTO_SYNC_FIRST_DELAY 30
#define NTP_AUTO_SYNC_PERIOD 30
#define NETUTILS_NTP_HOSTNAME "cn.ntp.org.cn"
#define NETUTILS_NTP_HOSTNAME2 "ntp.rt-thread.org"
#define NETUTILS_NTP_HOSTNAME3 "edu.ntp.org.cn"
#define PKG_USING_NETUTILS_LATEST_VERSION
#define PKG_NETUTILS_VER_NUM 0x99999

/* IoT Cloud */

/* end of IoT Cloud */
#define PKG_USING_PROTOBUF_C
#define PKG_USING_PROTOBUF_C_LATEST_VERSION
#define PKG_PROTOBUF_C_VER_NUM 0x99999
#define PKG_USING_SMTP_CLIENT
#define PKG_USING_SMTP_CLIENT_LATEST_VERSION
#define SMTP_CLIENT_USING_TLS
#define SMTP_CLIENT_ENABLE_DEBUG_LOG

/* smtp_client Options */

#define SMTP_CLIENT_USING_SAMPLE
#define SMTP_CLIENT_USING_ATTACHMENT
/* end of smtp_client Options */
/* end of IoT - internet of things */

/* security packages */

#define PKG_USING_MBEDTLS

/* Select Root Certificate */

#define PKG_USING_MBEDTLS_USER_CERTS
#define PKG_USING_MBEDTLS_DIGICERT_ROOT_CA
#define PKG_USING_MBEDTLS_CLOBALSIGN_ROOT_CA
/* end of Select Root Certificate */
#define MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_ECP_WINDOW_SIZE 2
#define MBEDTLS_SSL_MAX_CONTENT_LEN 8192
#define PKG_USING_MBEDTLS_V2281
/* end of security packages */

/* language packages */

/* JSON: JavaScript Object Notation, a lightweight data-interchange format */

#define PKG_USING_CJSON
#define PKG_USING_CJSON_V1717
/* end of JSON: JavaScript Object Notation, a lightweight data-interchange format */

/* XML: Extensible Markup Language */

/* end of XML: Extensible Markup Language */
/* end of language packages */

/* multimedia packages */

/* LVGL: powerful and easy-to-use embedded GUI library */

#define PKG_USING_LVGL
#define PKG_LVGL_THREAD_PRIO 20
#define PKG_LVGL_THREAD_STACK_SIZE 15200
#define PKG_LVGL_DISP_REFR_PERIOD 5
#define PKG_LVGL_USING_V080310
#define PKG_LVGL_VER_NUM 0x080310
#define PKG_USING_LV_MUSIC_DEMO
/* end of LVGL: powerful and easy-to-use embedded GUI library */

/* u8g2: a monochrome graphic library */

/* end of u8g2: a monochrome graphic library */
/* end of multimedia packages */

/* tools packages */

/* end of tools packages */

/* system packages */

/* enhanced kernel services */

#define PKG_USING_RT_VSNPRINTF_FULL
#define PKG_VSNPRINTF_SUPPORT_DECIMAL_SPECIFIERS
#define PKG_VSNPRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS
#define PKG_VSNPRINTF_SUPPORT_WRITEBACK_SPECIFIER
#define PKG_VSNPRINTF_SUPPORT_LONG_LONG
#define PKG_VSNPRINTF_CHECK_FOR_NUL_IN_FORMAT_SPECIFIER
#define PKG_VSNPRINTF_INTEGER_BUFFER_SIZE 32
#define PKG_VSNPRINTF_DECIMAL_BUFFER_SIZE 32
#define PKG_VSNPRINTF_DEFAULT_FLOAT_PRECISION 6
#define PKG_VSNPRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL 9
#define PKG_VSNPRINTF_LOG10_TAYLOR_TERMS 4
#define PKG_USING_RT_VSNPRINTF_FULL_LATEST_VERSION
/* end of enhanced kernel services */

/* acceleration: Assembly language or algorithmic acceleration packages */

/* end of acceleration: Assembly language or algorithmic acceleration packages */

/* CMSIS: ARM Cortex-M Microcontroller Software Interface Standard */

#define PKG_USING_CMSIS_NN
#define PKG_USING_CMSIS_NN_LATEST_VERSION
/* end of CMSIS: ARM Cortex-M Microcontroller Software Interface Standard */

/* Micrium: Micrium software products porting for RT-Thread */

/* end of Micrium: Micrium software products porting for RT-Thread */
#define PKG_USING_PERF_COUNTER
#define PKG_USING_PERF_COUNTER_V2241
/* end of system packages */

/* peripheral libraries and drivers */

/* HAL & SDK Drivers */

/* STM32 HAL & SDK Drivers */

/* end of STM32 HAL & SDK Drivers */

/* Infineon HAL Packages */

/* end of Infineon HAL Packages */

/* Kendryte SDK */

/* end of Kendryte SDK */

/* WCH HAL & SDK Drivers */

/* end of WCH HAL & SDK Drivers */

/* AT32 HAL & SDK Drivers */

/* end of AT32 HAL & SDK Drivers */

/* HC32 DDL Drivers */

/* end of HC32 DDL Drivers */

/* NXP HAL & SDK Drivers */

/* end of NXP HAL & SDK Drivers */

/* NUVOTON Drivers */

/* end of NUVOTON Drivers */

/* GD32 Drivers */

/* end of GD32 Drivers */
/* end of HAL & SDK Drivers */

/* sensors drivers */

#define PKG_USING_BH1750
#define PKG_USING_BH1750_LATEST_VERSION
/* end of sensors drivers */

/* touch drivers */

#define PKG_USING_GT911
#define PKG_USING_GT911_LATEST_VERSION
/* end of touch drivers */
#define PKG_USING_I2C_TOOLS
#define PKG_USING_I2C_TOOLS_LATEST_VERSION
#define PKG_USING_ST7789
#define PKG_ST_7789_SPI_BUS_NAME "spi0"
#define PKG_ST_7789_SPI_DEVICE_NAME "spi01"
#define PKG_ST_7789_WIDTH 240
#define PKG_ST_7789_HEIGHT 320
#define PKG_ST_7789_DC_PIN 46
#define PKG_ST_7789_RES_PIN 47
#define PKG_ST_7789_CS_PIN 05
#define PKG_ST_7789_BLK_PIN 103
#define PKG_USING_SERVO
#define PKG_USING_SG90
#define PKG_USING_SG90_DEMO
#define PKG_USING_PWM_DEV_NAME "pwm0"
#define PKG_USING_PWM_DEV_CHANNEL 0
#define PKG_USING_MAX_ANGLE 2500000
#define PKG_USING_MIN_ANGLE 500000
#define PKG_USING_SG90_MAX_ANGLE 180
#define PKG_USING_SG90_PERIOD 20000000
#define PKG_USING_SERVO_V100
/* end of peripheral libraries and drivers */

/* AI packages */

#define PKG_USING_NNOM
#define PKG_USING_NNOM_V043
#define PKG_USING_ONNX_BACKEND
#define PKG_USING_ONNX_BACKEND_LATEST_VERSION
#define PKG_ONNX_BACKEND_VER_NUM 0x99999
#define PKG_USING_ONNX_PARSER
#define PKG_USING_ONNX_PARSER_LATEST_VERSION
#define PKG_ONNX_PARSER_VER_NUM 0x99999
#define PKG_USING_LLMCHAT
#define PKG_LLM_USING_DOUBAO_CLOUD
#define PKG_LLM_API_KEY "sk-d79900af02734fb1b667b7214d76ac8a"
#define PKG_LLM_MODEL_NAME "deepseek-v3"
#define PKG_LLM_DOUBAO_API_URL "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
#define PKG_LLM_THREAD_STACK_SIZE 10240
#define PKG_LLM_CMD_BUFFER_SIZE 1024
#define PKG_WEB_SORKET_BUFSZ 4096
#define PKG_LLMCHAT_STREAM
#define PKG_LLMCHAT_DBG

/* Enable llmchat example */

#define PKG_USING_LLMCHAT_DEMO
/* end of Enable llmchat example */
#define PKG_USING_LLMCHAT_LATEST_VERSION
/* end of AI packages */

/* Signal Processing and Control Algorithm Packages */

/* end of Signal Processing and Control Algorithm Packages */

/* miscellaneous packages */

/* project laboratory */

/* end of project laboratory */

/* samples: kernel and components samples */

/* end of samples: kernel and components samples */

/* entertainment: terminal games and other interesting software packages */

/* end of entertainment: terminal games and other interesting software packages */
/* end of miscellaneous packages */

/* Arduino libraries */

#define PKG_USING_RTDUINO
#define RTDUINO_THREAD_SIZE 2048
#define RTDUINO_THREAD_PRIO 30
#define RTDUINO_SUPPORT_HIGH_PRECISION_MICROS
#define RTDUINO_USING_WIRE
#define RTDUINO_WIRE_BUFFER_LENGTH 32
#define RTDUINO_USING_SPI
#define RTDUINO_USING_SERVO
#define PKG_USING_RTDUINO_LATEST_VERSION

/* Projects and Demos */

/* end of Projects and Demos */

/* Sensors */

#define PKG_USING_ARDUINO_ADAFRUIT_SENSOR
#define PKG_USING_ARDUINO_ADAFRUIT_SENSOR_LATEST_VERSION
#define PKG_USING_ARDUINO_ADAFRUIT_BMP280
#define PKG_USING_ARDUINO_ADAFRUIT_BMP280_LATEST_VERSION
#define PKG_USING_ARDUINO_ADAFRUIT_SHT31
#define PKG_USING_ARDUINO_ADAFRUIT_SHT31_LATEST_VERSION
/* end of Sensors */

/* Display */

/* end of Display */

/* Timing */

/* end of Timing */

/* Data Processing */

/* end of Data Processing */

/* Data Storage */

/* Communication */

/* end of Communication */

/* Device Control */

/* end of Device Control */

/* Other */

/* end of Other */

/* Signal IO */

#define PKG_USING_ARDUINO_ADAFRUIT_BUSIO
#define PKG_USING_ARDUINO_ADAFRUIT_BUSIO_LATEST_VERSION
/* end of Signal IO */

/* Uncategorized */

/* end of Arduino libraries */
/* end of RT-Thread online packages */
#define SOC_FAMILY_IFX
#define SOC_SERIES_IFX_PSOC62

/* Hardware Drivers Config */

#define SOC_CY8C624ALQI_S2D42

/* Onboard Peripheral Drivers */

#define BSP_USING_USB_TO_USART
#define BSP_USING_ARDUINO
/* end of Onboard Peripheral Drivers */

/* On-chip Peripheral Drivers */

#define BSP_USING_GPIO
#define BSP_USING_UART
#define BSP_USING_UART1
#define BSP_USING_UART5
#define BSP_USING_UART6
#define BSP_USING_PWM
#define BSP_USING_PWM0
#define BSP_USING_PWM0_CH0
#define BSP_USING_PWM0_CH0_PORT10
#define BSP_USING_PWM0_CH2
#define BSP_USING_PWM0_CH2_PORT11_COMPL
#define BSP_USING_PWM0_CH3
#define BSP_USING_PWM0_CH4
#define BSP_USING_PWM0_CH4_PORT5_COMPL
#define BSP_USING_PWM0_CH7
#define BSP_USING_PWM1
#define BSP_USING_PWM1_CH0
#define BSP_USING_PWM1_CH0_PORT10_COMPL
#define BSP_USING_SPI
#define BSP_USING_SPI0
#define BSP_USING_HW_I2C
#define BSP_USING_HW_I2C4

/* Notice: P8_0 --> 64; P8_1 --> 65 */

#define BSP_I2C4_SCL_PIN 64
#define BSP_I2C4_SDA_PIN 65
#define BSP_USING_RTC
#define BSP_RTC_USING_LSI
#define BSP_USING_WDT
#define BSP_USING_SDMMC
#define BSP_USING_SDCARD
#define BSP_USING_SDCARD_BUS_WIDTH 4
#define BSP_USING_SDCARD_PIN_CONFIG
#define BSP_USING_SDCARD_CMD_PIN 20
#define BSP_USING_SDCARD_CLK_PIN 21
#define BSP_USING_SDCARD_DAT0_PIN 16
#define BSP_USING_SDCARD_DAT1_PIN 17
#define BSP_USING_SDCARD_DAT2_PIN 18
#define BSP_USING_SDCARD_DAT3_PIN 19
#define BSP_USING_SDCARD_DAT4_PIN -1
#define BSP_USING_SDCARD_DAT5_PIN -1
#define BSP_USING_SDCARD_DAT6_PIN -1
#define BSP_USING_SDCARD_DAT7_PIN -1
#define BSP_USING_SDCARD_DETECT_PIN 22
#define BSP_USING_SDCARD_IO_VOLT_SEL_PIN -1
#define BSP_USING_SDCARD_CARD_IF_PWR_EN_PIN -1
#define BSP_USING_SDCARD_CARD_MECH_WRITE_PROT_PIN -1
#define BSP_USING_SDCARD_CARD_EMMC_RESET_PIN -1
#define BSP_USING_LVGL
#define BSP_USING_LVGL_DEMO
/* end of On-chip Peripheral Drivers */

/* Board extended module Drivers */

#define BSP_USING_RW007

/* Notice: P5_7 --> 47; P5_6 -->46; P0_5 --> 5; P0_4 --> 4 */

#define IFX_RW007_SPI_BUS_NAME "spi0"
#define IFX_RW007_WIFI_SSID "t"
#define IFX_RW007_WIFI_PASSWORD "20050424"
#define IFX_RW007_CS_PIN 40
#define IFX_RW007_BOOT0_PIN 4
#define IFX_RW007_BOOT1_PIN 40
#define IFX_RW007_INT_BUSY_PIN 90
#define IFX_RW007_RST_PIN 46
/* end of Board extended module Drivers */
/* end of Hardware Drivers Config */

#endif
