################################################################################
# 自动生成的文件。不要编辑！
################################################################################

-include ../makefile.init

RM := rm -rf

# All of the sources participating in the build are defined here
-include sources.mk
-include rt-thread/src/subdir.mk
-include rt-thread/libcpu/arm/cortex-m4/subdir.mk
-include rt-thread/libcpu/arm/common/subdir.mk
-include rt-thread/components/utilities/resource/subdir.mk
-include rt-thread/components/net/sal/src/subdir.mk
-include rt-thread/components/net/sal/socket/subdir.mk
-include rt-thread/components/net/sal/impl/subdir.mk
-include rt-thread/components/net/sal/dfs_net/subdir.mk
-include rt-thread/components/net/netdev/src/subdir.mk
-include rt-thread/components/net/lwip/port/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/netif/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/core/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/apps/ping/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/api/subdir.mk
-include rt-thread/components/libc/posix/io/poll/subdir.mk
-include rt-thread/components/libc/cplusplus/subdir.mk
-include rt-thread/components/libc/compilers/newlib/subdir.mk
-include rt-thread/components/libc/compilers/common/subdir.mk
-include rt-thread/components/finsh/subdir.mk
-include rt-thread/components/drivers/wlan/subdir.mk
-include rt-thread/components/drivers/watchdog/subdir.mk
-include rt-thread/components/drivers/touch/subdir.mk
-include rt-thread/components/drivers/spi/subdir.mk
-include rt-thread/components/drivers/serial/subdir.mk
-include rt-thread/components/drivers/sensor/v1/subdir.mk
-include rt-thread/components/drivers/sdio/subdir.mk
-include rt-thread/components/drivers/rtc/subdir.mk
-include rt-thread/components/drivers/misc/subdir.mk
-include rt-thread/components/drivers/ipc/subdir.mk
-include rt-thread/components/drivers/i2c/subdir.mk
-include rt-thread/components/dfs/dfs_v1/src/subdir.mk
-include rt-thread/components/dfs/dfs_v1/filesystems/elmfat/subdir.mk
-include rt-thread/components/dfs/dfs_v1/filesystems/devfs/subdir.mk
-include packages/webclient-v2.2.0/src/subdir.mk
-include packages/smtp_client-latest/src/subdir.mk
-include packages/smtp_client-latest/example/subdir.mk
-include packages/rw007-v2.1.0/src/subdir.mk
-include packages/rt_vsnprintf_full-latest/subdir.mk
-include packages/protobuf-c-latest/src/subdir.mk
-include packages/perf_counter-v2.2.4.1/os/subdir.mk
-include packages/perf_counter-v2.2.4.1/subdir.mk
-include packages/pahomqtt-latest/samples/subdir.mk
-include packages/pahomqtt-latest/MQTTPacket/src/subdir.mk
-include packages/pahomqtt-latest/MQTTClient-RT/subdir.mk
-include packages/onnx-parser-latest/src/subdir.mk
-include packages/onnx-backend-latest/src/subdir.mk
-include packages/nnom-v0.4.3/src/layers/subdir.mk
-include packages/nnom-v0.4.3/src/core/subdir.mk
-include packages/nnom-v0.4.3/src/backends/subdir.mk
-include packages/netutils-latest/ntp/subdir.mk
-include packages/mbedtls-v2.28.1/ports/src/subdir.mk
-include packages/mbedtls-v2.28.1/mbedtls/library/subdir.mk
-include packages/lv_music_demo-v0.3.4/assets/subdir.mk
-include packages/lv_music_demo-v0.3.4/subdir.mk
-include packages/llmchat-latest/ports/subdir.mk
-include packages/llmchat-latest/demo/subdir.mk
-include packages/llmchat-latest/subdir.mk
-include packages/i2c-tools-latest/src/subdir.mk
-include packages/gt911-latest/src/subdir.mk
-include packages/cJSON-v1.7.17/subdir.mk
-include packages/bh1750-latest/subdir.mk
-include packages/Servo_sg90-v1.0.0/subdir.mk
-include packages/RTduino-latest/libraries/buildin/Wire/subdir.mk
-include packages/RTduino-latest/libraries/buildin/Servo/subdir.mk
-include packages/RTduino-latest/libraries/buildin/SPI/subdir.mk
-include packages/RTduino-latest/core/avr/subdir.mk
-include packages/RTduino-latest/core/subdir.mk
-include packages/LVGL-v8.3.10/src/widgets/subdir.mk
-include packages/LVGL-v8.3.10/src/misc/subdir.mk
-include packages/LVGL-v8.3.10/src/hal/subdir.mk
-include packages/LVGL-v8.3.10/src/font/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/win/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/tileview/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/tabview/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/spinner/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/spinbox/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/span/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/msgbox/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/meter/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/menu/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/list/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/led/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/keyboard/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/imgbtn/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/colorwheel/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/chart/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/calendar/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/widgets/animimg/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/themes/mono/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/themes/default/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/themes/basic/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/others/snapshot/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/others/msg/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/others/monkey/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/others/imgfont/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/others/ime/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/others/gridnav/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/others/fragment/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/sjpg/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/rlottie/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/qrcode/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/png/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/gif/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/fsdrv/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/freetype/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/ffmpeg/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/libs/bmp/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/layouts/grid/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/layouts/flex/subdir.mk
-include packages/LVGL-v8.3.10/src/extra/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/swm341_dma2d/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/sw/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/stm32_dma2d/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/sdl/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/renesas/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/nxp/vglite/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/nxp/pxp/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/arm2d/subdir.mk
-include packages/LVGL-v8.3.10/src/draw/subdir.mk
-include packages/LVGL-v8.3.10/src/core/subdir.mk
-include packages/LVGL-v8.3.10/env_support/rt-thread/subdir.mk
-include packages/Adafruit-Sensor-latest/subdir.mk
-include packages/Adafruit-SHT31-latest/subdir.mk
-include packages/Adafruit-BusIO-latest/subdir.mk
-include packages/Adafruit-BMP280-latest/subdir.mk
-include libs/TARGET_RTT-062S2/config/GeneratedSource/subdir.mk
-include libs/TARGET_RTT-062S2/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/subdir.mk
-include libs/TARGET_RTT-062S2/COMPONENT_CM4/subdir.mk
-include libs/TARGET_RTT-062S2/subdir.mk
-include libraries/IFX_PSOC6_HAL/retarget-io/subdir.mk
-include libraries/IFX_PSOC6_HAL/psoc6cm0p/COMPONENT_CM0P_SLEEP/subdir.mk
-include libraries/IFX_PSOC6_HAL/mtb-pdl-cat1/drivers/source/TOOLCHAIN_GCC_ARM/subdir.mk
-include libraries/IFX_PSOC6_HAL/mtb-pdl-cat1/drivers/source/subdir.mk
-include libraries/IFX_PSOC6_HAL/mtb-pdl-cat1/devices/COMPONENT_CAT1A/source/subdir.mk
-include libraries/IFX_PSOC6_HAL/mtb-hal-cat1/source/subdir.mk
-include libraries/IFX_PSOC6_HAL/mtb-hal-cat1/COMPONENT_CAT1A/source/triggers/subdir.mk
-include libraries/IFX_PSOC6_HAL/mtb-hal-cat1/COMPONENT_CAT1A/source/pin_packages/subdir.mk
-include libraries/HAL_Drivers/subdir.mk
-include board/ports/subdir.mk
-include board/GUI/subdir.mk
-include board/subdir.mk
-include applications/model_int/subdir.mk
-include applications/lvgl/demo/subdir.mk
-include applications/arduino_pinout/subdir.mk
-include applications/Hardware/subdir.mk
-include applications/subdir.mk
-include subdir.mk
-include objects.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(CC_DEPS)),)
-include $(CC_DEPS)
endif
ifneq ($(strip $(C++_DEPS)),)
-include $(C++_DEPS)
endif
ifneq ($(strip $(C_UPPER_DEPS)),)
-include $(C_UPPER_DEPS)
endif
ifneq ($(strip $(CXX_DEPS)),)
-include $(CXX_DEPS)
endif
ifneq ($(strip $(ASM_DEPS)),)
-include $(ASM_DEPS)
endif
ifneq ($(strip $(S_DEPS)),)
-include $(S_DEPS)
endif
ifneq ($(strip $(S_UPPER_DEPS)),)
-include $(S_UPPER_DEPS)
endif
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
ifneq ($(strip $(CPP_DEPS)),)
-include $(CPP_DEPS)
endif
endif

-include ../makefile.defs

# Add inputs and outputs from these tool invocations to the build variables 
SECONDARY_FLASH += \
rtthread.hex \

SECONDARY_SIZE += \
rtthread.siz \


# 所有目标
all: rtthread.elf secondary-outputs

# 工具调用
rtthread.elf: $(OBJS) $(USER_OBJS)
	@$(file >link.temp, -T "../board/linker_scripts/link.ld" -Xlinker --gc-sections -Wl,-Map,"rtthread.map" -Xlinker --cref --specs=nano.specs -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -Wl,--gc-sections,-Map=rtthread.map,-cref,-u,Reset_Handler -o "rtthread.elf" $(OBJS) $(USER_OBJS) $(LIBS)) project_linker.exe link.temp arm-none-eabi-g++

rtthread.hex: rtthread.elf
	arm-none-eabi-objcopy -O ihex "rtthread.elf"  "rtthread.hex"

rtthread.siz: rtthread.elf
	arm-none-eabi-size --format=berkeley "rtthread.elf"

# 其他目标
clean:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(OBJS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS) rtthread.elf
	-@echo ' '

secondary-outputs: $(SECONDARY_FLASH) $(SECONDARY_SIZE)

.PHONY: all clean dependents

-include ../makefile.targets
