################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications \
applications/Hardware \
applications/arduino_pinout \
applications/lvgl/demo \
applications/model_int \
board/GUI \
board \
board/ports \
libraries/HAL_Drivers \
libraries/IFX_PSOC6_HAL/mtb-hal-cat1/COMPONENT_CAT1A/source/pin_packages \
libraries/IFX_PSOC6_HAL/mtb-hal-cat1/COMPONENT_CAT1A/source/triggers \
libraries/IFX_PSOC6_HAL/mtb-hal-cat1/source \
libraries/IFX_PSOC6_HAL/mtb-pdl-cat1/devices/COMPONENT_CAT1A/source \
libraries/IFX_PSOC6_HAL/mtb-pdl-cat1/drivers/source/TOOLCHAIN_GCC_ARM \
libraries/IFX_PSOC6_HAL/mtb-pdl-cat1/drivers/source \
libraries/IFX_PSOC6_HAL/psoc6cm0p/COMPONENT_CM0P_SLEEP \
libraries/IFX_PSOC6_HAL/retarget-io \
libs/TARGET_RTT-062S2/COMPONENT_CM4/TOOLCHAIN_GCC_ARM \
libs/TARGET_RTT-062S2/COMPONENT_CM4 \
libs/TARGET_RTT-062S2/config/GeneratedSource \
libs/TARGET_RTT-062S2 \
packages/Adafruit-BMP280-latest \
packages/Adafruit-BusIO-latest \
packages/Adafruit-SHT31-latest \
packages/Adafruit-Sensor-latest \
packages/LVGL-v8.3.10/env_support/rt-thread \
packages/LVGL-v8.3.10/src/core \
packages/LVGL-v8.3.10/src/draw/arm2d \
packages/LVGL-v8.3.10/src/draw \
packages/LVGL-v8.3.10/src/draw/nxp/pxp \
packages/LVGL-v8.3.10/src/draw/nxp/vglite \
packages/LVGL-v8.3.10/src/draw/renesas \
packages/LVGL-v8.3.10/src/draw/sdl \
packages/LVGL-v8.3.10/src/draw/stm32_dma2d \
packages/LVGL-v8.3.10/src/draw/sw \
packages/LVGL-v8.3.10/src/draw/swm341_dma2d \
packages/LVGL-v8.3.10/src/extra/layouts/flex \
packages/LVGL-v8.3.10/src/extra/layouts/grid \
packages/LVGL-v8.3.10/src/extra/libs/bmp \
packages/LVGL-v8.3.10/src/extra/libs/ffmpeg \
packages/LVGL-v8.3.10/src/extra/libs/freetype \
packages/LVGL-v8.3.10/src/extra/libs/fsdrv \
packages/LVGL-v8.3.10/src/extra/libs/gif \
packages/LVGL-v8.3.10/src/extra/libs/png \
packages/LVGL-v8.3.10/src/extra/libs/qrcode \
packages/LVGL-v8.3.10/src/extra/libs/rlottie \
packages/LVGL-v8.3.10/src/extra/libs/sjpg \
packages/LVGL-v8.3.10/src/extra \
packages/LVGL-v8.3.10/src/extra/others/fragment \
packages/LVGL-v8.3.10/src/extra/others/gridnav \
packages/LVGL-v8.3.10/src/extra/others/ime \
packages/LVGL-v8.3.10/src/extra/others/imgfont \
packages/LVGL-v8.3.10/src/extra/others/monkey \
packages/LVGL-v8.3.10/src/extra/others/msg \
packages/LVGL-v8.3.10/src/extra/others/snapshot \
packages/LVGL-v8.3.10/src/extra/themes/basic \
packages/LVGL-v8.3.10/src/extra/themes/default \
packages/LVGL-v8.3.10/src/extra/themes/mono \
packages/LVGL-v8.3.10/src/extra/widgets/animimg \
packages/LVGL-v8.3.10/src/extra/widgets/calendar \
packages/LVGL-v8.3.10/src/extra/widgets/chart \
packages/LVGL-v8.3.10/src/extra/widgets/colorwheel \
packages/LVGL-v8.3.10/src/extra/widgets/imgbtn \
packages/LVGL-v8.3.10/src/extra/widgets/keyboard \
packages/LVGL-v8.3.10/src/extra/widgets/led \
packages/LVGL-v8.3.10/src/extra/widgets/list \
packages/LVGL-v8.3.10/src/extra/widgets/menu \
packages/LVGL-v8.3.10/src/extra/widgets/meter \
packages/LVGL-v8.3.10/src/extra/widgets/msgbox \
packages/LVGL-v8.3.10/src/extra/widgets/span \
packages/LVGL-v8.3.10/src/extra/widgets/spinbox \
packages/LVGL-v8.3.10/src/extra/widgets/spinner \
packages/LVGL-v8.3.10/src/extra/widgets/tabview \
packages/LVGL-v8.3.10/src/extra/widgets/tileview \
packages/LVGL-v8.3.10/src/extra/widgets/win \
packages/LVGL-v8.3.10/src/font \
packages/LVGL-v8.3.10/src/hal \
packages/LVGL-v8.3.10/src/misc \
packages/LVGL-v8.3.10/src/widgets \
packages/RTduino-latest/core \
packages/RTduino-latest/core/avr \
packages/RTduino-latest/libraries/buildin/SPI \
packages/RTduino-latest/libraries/buildin/Servo \
packages/RTduino-latest/libraries/buildin/Wire \
packages/Servo_sg90-v1.0.0 \
packages/bh1750-latest \
packages/cJSON-v1.7.17 \
packages/gt911-latest/src \
packages/i2c-tools-latest/src \
packages/llmchat-latest/demo \
packages/llmchat-latest \
packages/llmchat-latest/ports \
packages/lv_music_demo-v0.3.4/assets \
packages/lv_music_demo-v0.3.4 \
packages/mbedtls-v2.28.1/mbedtls/library \
packages/mbedtls-v2.28.1/ports/src \
packages/netutils-latest/ntp \
packages/nnom-v0.4.3/src/backends \
packages/nnom-v0.4.3/src/core \
packages/nnom-v0.4.3/src/layers \
packages/onnx-backend-latest/src \
packages/onnx-parser-latest/src \
packages/pahomqtt-latest/MQTTClient-RT \
packages/pahomqtt-latest/MQTTPacket/src \
packages/pahomqtt-latest/samples \
packages/perf_counter-v2.2.4.1/os \
packages/perf_counter-v2.2.4.1 \
packages/protobuf-c-latest/src \
packages/rt_vsnprintf_full-latest \
packages/rw007-v2.1.0/src \
packages/smtp_client-latest/example \
packages/smtp_client-latest/src \
packages/webclient-v2.2.0/src \
rt-thread/components/dfs/dfs_v1/filesystems/devfs \
rt-thread/components/dfs/dfs_v1/filesystems/elmfat \
rt-thread/components/dfs/dfs_v1/src \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/rtc \
rt-thread/components/drivers/sdio \
rt-thread/components/drivers/sensor/v1 \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi \
rt-thread/components/drivers/touch \
rt-thread/components/drivers/watchdog \
rt-thread/components/drivers/wlan \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/libc/cplusplus \
rt-thread/components/libc/posix/io/poll \
rt-thread/components/net/lwip/lwip-2.0.3/src/api \
rt-thread/components/net/lwip/lwip-2.0.3/src/apps/ping \
rt-thread/components/net/lwip/lwip-2.0.3/src/core \
rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4 \
rt-thread/components/net/lwip/lwip-2.0.3/src/netif \
rt-thread/components/net/lwip/port \
rt-thread/components/net/netdev/src \
rt-thread/components/net/sal/dfs_net \
rt-thread/components/net/sal/impl \
rt-thread/components/net/sal/socket \
rt-thread/components/net/sal/src \
rt-thread/components/utilities/resource \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-m4 \
rt-thread/src \

